# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
# This file is *NOT* reloaded automatically when you use 'bundle exec jekyll serve'.
# If you change this file, please restart the server process.

# Site settings
# are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

#theme: jekyll-agency

url: https://twin-tech.at
baseurl:

title      : "Twin Tech"
email      : daniel.lehner@twin-tech.at #this is also the email contact forms will go to
description: "Your partner to accellerate your digitalization and innovation efforts with digital twins."
author     : Twin Tech Daniel Lehner
logo:     #optional, defaults to site title
   path: assets\img\logos\TwinTech.png
   height: 60 #height in px, defaults to 52px


# SK: HAS TO BE SET !!!
# Removed redundancy, to increase.
locale: "en-US" # See available languages in _data/sitetext.yml

analytics:
  google: #Google Analytics tracking code here

collections:
  portfolio:
  services:
    output: true
    permalink: /:path/

markdown: kramdown

# Uncomment following line to use Formspree form ID based URL instead of email based URL
# Details: https://help.formspree.io/hc/en-us/articles/360017735154-How-to-prevent-spam
# formspree_form_path: "f/a_form_id"

people:
  - name: Dr. Daniel Lehner
    role: Owner, Digital Twin Evangelist
    image: assets/img/team/DanielLehner2.jpg
    social:
      - url: https://derlehner.at/
        icon: fa fa-home
      - url: https://se.jku.at/daniel-lehner
        icon: fa fa-university
      - url: https://www.linkedin.com/in/daniel-lehner-95710a71/
        icon: fab fa-linkedin-in
    cv:
      - text: Spent the last 5 years <br/>investigating and developing <br/><b><span class="text-success">Digital Twin platforms</span></b>
      - text: Organizer of the <br/><b><a href="https://edt.community/"><span class="text-success">Engineering Digital Twins Community</span></a></b>
      - text: Articles with <b><span class="text-success"> > 150.000 readers</span></b> in heise iX, informatik aktuell, coders kitchen, …
  - name: "Dr. Stefan Klikovits"
    role: The Tech Enthusiast
    image: assets/img/team/StefanKlikovits.jpg
    social:
      - url: https://klikovits.net
        icon: fa fa-home
      - url: https://se.jku.at/stefan-klikovits
        icon: fas fa-university
      - url: https://www.linkedin.com/in/stefan.klikovits
        icon: fab fa-linkedin-in
    cv:
      - text: 15+ years of <b><span class="text-success">V&V</span></b> of <b><span class="text-success">Large, Complex & Distributed CPSs</span></b>
      - text: Pushing the boundaries of <b><span class="text-success">Digital Twins, MDE, Autonomous Driving</span></b> and <b><span class="text-success">Quantum SE</span></b> research
      - text: <b><span class="text-success">12+ years of international experience</span></b> at CERN, BBC, and National Institute of Informatics (Tokyo)
  - name: Martin Eisenberg
    role: The AI Guy
    image: assets/img/team/martin_eisenberg.jpeg
    social:
      - url: https://se.jku.at/martin-eisenberg
        icon: fa fa-university
      - url: https://www.linkedin.com/in/martin-eisenberg-45b224245/
        icon: fab fa-linkedin-in
    cv:
      - text: Worked the last 4 years on implementing AI use cases
      - text: Tames Neural Networks and Genetic Algorithms for breakfast
  - name: Edvin Herac
    role: Systems and Complexity Manager
    image: assets/img/team/edvin_herac.png
    social:
      - url: https://edvher.github.io/
        icon: fa fa-university
      - url: https://www.linkedin.com/in/edvin-herac-946b382bb/
        icon: fab fa-linkedin-in
    cv:
      - text: 5 years of taming complex systems through version and variant management
      - text: 10+ years of experience in software engineering with ERP, PDM and CAD systems
      - text: Manages cross-functional teams
  - name: Prof. Reinhold Plösch
    role: Innovation and Funding Advisor
    image: assets/img/team/reinhold_ploesch.jpg
    social:
      - url: https://se.jku.at/reinhold-ploesch/
        icon: fa fa-home
      - url: https://www.linkedin.com/in/reinhold-pl%C3%B6sch-2b969a41/
        icon: fab fa-linkedin-in
    cv:
     - text: Combines Large Language Models with traditional Quality Assurance techniques in his daily work
     - text: Academic director of IPO (knowledge transfer hub in Upper Austria)
     - text: Headed multiple international projects with partners including Siemens, Capgemini, and SAP
  - name: "Prof. Dr. Manuel Wimmer"
    role: "Scientific Advisor"
    image: assets/img/team/ManuelWimmer.png
    social:
      - url: https://se.jku.at/manuel-wimmer/
        icon: fa fa-university
    cv: 
      - text: <b><span class="text-success">20+ years of experience</span></b> in advancing the practice of software engineering through science
      - text: "publications with <b><span class='text-success'>> 10.000 Citations</span></b>"
      - text: Author of <b><a href="https://mdse-book.com/"><span class="text-success">"MDSE in Practice"</span></a></b>

memberships:
  - name: "Open Industry 4.0 Alliance"
    logo: assets/img/logos/oi4.png
  - name: "Mechatronikcluster Oberösterreich"
    logo: assets/img/logos/mc.png
  - name: "OPC Foundation"
    logo: assets/img/logos/opc.png

toolpartners:
  - name: XITASO GmbH
    logo: assets/img/logos/xitaso.png
  - name: Digital Twin Factory
    logo: assets/img/logos/dtf.png
  - name: DCCX GmbH
    logo: assets/img/logos/xitaso.png


social:
  - url: mailto:office@twin-tech.at
    icon: "fa fa-at"
  - url: https://www.linkedin.com/company/twintech-at/
    icon: "fab fa-linkedin"
