# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
# This file is *NOT* reloaded automatically when you use 'bundle exec jekyll serve'.
# If you change this file, please restart the server process.

# Site settings
# are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

#theme: jekyll-agency

url: https://twin-tech.at
baseurl:

title      : "Twin Tech"
email      : daniel.lehner@twin-tech.at #this is also the email contact forms will go to
description: "Your partner to accellerate your digitalization and innovation efforts with digital twins."
author     : Twin Tech Daniel Lehner
logo:     #optional, defaults to site title
   path: assets\img\logos\TwinTech.png
   height: 60 #height in px, defaults to 52px


# SK: HAS TO BE SET !!!
# Removed redundancy, to increase.
locale: "en-US" # See available languages in _data/sitetext.yml

analytics:
  google: #Google Analytics tracking code here

collections:
  portfolio:
  services:
    output: true
    permalink: /:path/

markdown: kramdown

# Uncomment following line to use Formspree form ID based URL instead of email based URL
# Details: https://help.formspree.io/hc/en-us/articles/360017735154-How-to-prevent-spam
# formspree_form_path: "f/a_form_id"

people:
  - name: DI Daniel Lehner
    role: Executive Officer
    image: assets/img/team/DanielLehner2.jpg
    social:
      - url: https://derlehner.at/
        icon: fa fa-home
      - url: https://se.jku.at/daniel-lehner
        icon: fa fa-university
      - url: https://www.linkedin.com/in/daniel-lehner-95710a71/
        icon: fab fa-linkedin-in
    cv:
      - text: Spent the last 5 years <br/>investigating and developing <br/><b><span class="text-success">Digital Twin platforms</span></b>
      - text: Organizer of the <br/><b><a href="https://edt.community/"><span class="text-success">Engineering Digital Twins Community</span></a></b>
      - text: Articles with <b><span class="text-success"> > 150.000 readers</span></b> in heise iX, informatik aktuell, coders kitchen, …
  - name: "Dr. Stefan Klikovits"
    role: "Technological Advisor"
    image: assets/img/team/StefanKlikovits.jpg
    social:
      - url: https://klikovits.net
        icon: fa fa-home
      - url: https://se.jku.at/stefan-klikovits
        icon: fas fa-university
      - url: https://www.linkedin.com/in/stefan.klikovits
        icon: fab fa-linkedin-in
    cv:
      - text: 17+ years of <b><span class="text-success">V&V</span></b> of <b><span class="text-success">Large, Complex & Distributed CPSs</span></b>
      - text: Pushing the boundaries of <b><span class="text-success">Digital Twins, MDE, Autonomous Driving</span></b> and <b><span class="text-success">Quantum SE</span></b> research
      - text: <b><span class="text-success">12+ years of international experience</span></b> at CERN, BBC, and National Institute of Informatics (Tokyo)

  - name: "Prof. Dr. Manuel Wimmer"
    role: "Scientific Advisor"
    image: assets/img/team/ManuelWimmer.png
    social:
      - url: https://se.jku.at/manuel-wimmer/
        icon: fa fa-university
    cv: 
      - text: <b><span class="text-success">20+ years of experience</span></b> in advancing the practice of software engineering through science
      - text: "publications with <b><span class='text-success'>> 10.000 Citations</span></b>"
      - text: Author of <b><a href="https://mdse-book.com/"><span class="text-success">"MDSE in Practice"</span></a></b>


partners:
  section: Kunden
  max-height: 150px
  horizontal-scrolling: "" #"yes/no"
  list:
    - title: "JKU"
      url: https://jku.at
      logo: assets/img/partners/winse-logo.png
    - title: "designmodo"
      url: https://github.com/raviriley/agency-jekyll-theme
      logo: assets/img/clients/designmodo.jpg
    - title: "themeforest"
      url: https://github.com/raviriley/agency-jekyll-theme
      logo: assets/img/clients/themeforest.jpg
    - title: "Creative Market"
      url: https://github.com/raviriley/agency-jekyll-theme
      logo: assets/img/clients/creative-market.jpg



social:
  - url: mailto:office@twin-tech.at
    icon: "fa fa-at"
  - url: https://www.linkedin.com/company/twintech-at/
    icon: "fab fa-linkedin"
